version = 1

test_patterns = ["test.js"]

exclude_patterns = ["/lib/*.js"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "mocha"
  ]
  dialect = "typescript"
